#!/usr/bin/env node
/**
 * ShipSafe After-Fix Test Generator
 * ==================================
 * Generates missing critical test cases for the AFTER state of the demo.
 * The Test Agent calls this to auto-generate security and validation tests.
 *
 * Usage:
 *   node scripts/generate-tests.js --project ./demo-app
 */

import fs from 'fs';
import path from 'path';

const args = process.argv.slice(2);
const projectPath = args[args.indexOf('--project') + 1] || './demo-app';
const absPath = path.resolve(projectPath);

const GENERATED_TESTS = `// ============================================================
// ShipSafe Auto-Generated Tests — AFTER state
// Generated by ShipSafe Test Agent to cover critical paths
// ============================================================

const request = require('supertest');
const { app, server } = require('../src/index');

// ── SEC-TEST-01: SQL Injection Rejection ──────────────────────────────────────
describe('Security: SQL Injection', () => {
  test('SQL injection attempt in login is rejected', async () => {
    const res = await request(app)
      .post('/api/users/login')
      .send({ username: "' OR 1=1 --", password: 'x' });
    expect(res.status).not.toBe(200);
    expect(res.body.token).toBeUndefined();
  });

  test('SQL injection via UNION in username is rejected', async () => {
    const res = await request(app)
      .post('/api/users/login')
      .send({ username: "admin' UNION SELECT * FROM users --", password: 'x' });
    expect(res.status).toBe(400);
  });
});

// ── SEC-TEST-02: Path Traversal Rejection ────────────────────────────────────
describe('Security: Path Traversal', () => {
  test('Path traversal in file query is rejected', async () => {
    const res = await request(app)
      .get('/api/products/image?file=../../etc/passwd');
    expect([400, 403]).toContain(res.status);
  });

  test('URL-encoded path traversal is rejected', async () => {
    const res = await request(app)
      .get('/api/products/image?file=..%2F..%2Fetc%2Fpasswd');
    expect([400, 403]).toContain(res.status);
  });
});

// ── SEC-TEST-03: Unauthenticated Access Rejection ────────────────────────────
describe('Security: Authentication', () => {
  test('Admin route without token returns 401', async () => {
    const res = await request(app).get('/api/users/all');
    expect(res.status).toBe(401);
  });

  test('Invalid JWT token returns 401', async () => {
    const res = await request(app)
      .get('/api/users/all')
      .set('Authorization', 'Bearer invalid.token.here');
    expect(res.status).toBe(401);
  });
});

// ── BIZ-TEST-01: Negative Amount Rejection ───────────────────────────────────
describe('Business Logic: Order Validation', () => {
  test('Negative order amount is rejected', async () => {
    const res = await request(app)
      .post('/api/orders')
      .send({ userId: 1, items: [], totalAmount: -999 });
    expect(res.status).toBe(400);
  });

  test('Zero amount order is rejected', async () => {
    const res = await request(app)
      .post('/api/orders')
      .send({ userId: 1, items: [], totalAmount: 0 });
    expect(res.status).toBe(400);
  });
});

// ── VAL-TEST-01: Input Validation ────────────────────────────────────────────
describe('Validation: Missing Required Fields', () => {
  test('Login with empty body returns 400', async () => {
    const res = await request(app).post('/api/users/login').send({});
    expect(res.status).toBe(400);
  });

  test('Register with missing password returns 400', async () => {
    const res = await request(app)
      .post('/api/users/register')
      .send({ username: 'testuser', email: 'test@test.com' });
    expect(res.status).toBe(400);
  });

  test('Register with missing username returns 400', async () => {
    const res = await request(app)
      .post('/api/users/register')
      .send({ email: 'test@test.com', password: 'password123' });
    expect(res.status).toBe(400);
  });
});

// ── ERR-TEST-01: Error Responses Don't Leak Details ──────────────────────────
describe('Error Handling: No Information Leakage', () => {
  test('Server errors do not expose DB error messages', async () => {
    // Trigger a predictable error with invalid product ID format
    const res = await request(app).get('/api/products/image?file=');
    if (res.status === 500) {
      expect(res.body.error).not.toMatch(/sqlite|SQLITE|syntax|column/i);
      expect(res.body).not.toHaveProperty('stack');
    }
  });
});

afterAll(() => {
  server.close();
});
`;

const testDir = path.join(absPath, 'tests');
if (!fs.existsSync(testDir)) fs.mkdirSync(testDir, { recursive: true });

const outPath = path.join(testDir, 'shipsafe-generated.test.js');
fs.writeFileSync(outPath, GENERATED_TESTS, 'utf8');

console.log(JSON.stringify({
  success: true,
  file_created: path.relative(absPath, outPath),
  tests_generated: 15,
  categories: ['SQL Injection', 'Path Traversal', 'Authentication', 'Business Logic', 'Validation', 'Error Handling'],
}));
